# Generated by Django 4.0.1 on 2022-01-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
